-- ============================================================
-- PayPal Payment Gateway Demo - Database Schema
-- Version: 1.0.0
-- Author: Shivam Srivastav
-- ============================================================

-- ============================================================
-- TABLE: orders
-- Purpose: Store customer orders before payment
-- ============================================================
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(500),
    subtotal DECIMAL(10, 2) NOT NULL,
    tax DECIMAL(10, 2) DEFAULT 0.00,
    shipping DECIMAL(10, 2) DEFAULT 0.00,
    total DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'USD',
    status VARCHAR(20) DEFAULT 'PENDING',
    customer_email VARCHAR(255),
    customer_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- TABLE: payments
-- Purpose: Store all payment transactions
-- Key Payment Concepts:
--   - payment_intent: CAPTURE (immediate) vs AUTHORIZE (hold)
--   - idempotency_key: Prevents duplicate payments
--   - captured_amount vs refunded_amount: Track partial operations
-- ============================================================
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- PayPal identifiers
    paypal_payment_id VARCHAR(100) UNIQUE,
    paypal_payer_id VARCHAR(100),
    paypal_order_id VARCHAR(100),
    paypal_capture_id VARCHAR(100),
    paypal_authorization_id VARCHAR(100),
    
    -- Link to our order
    order_id BIGINT,
    
    -- Payment details
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'USD',
    description VARCHAR(500),
    
    -- Payment intent: CAPTURE or AUTHORIZE
    payment_intent VARCHAR(20) DEFAULT 'CAPTURE',
    
    -- Payment status lifecycle
    -- CREATED -> APPROVED -> CAPTURED/AUTHORIZED -> COMPLETED/REFUNDED/VOIDED
    status VARCHAR(30) DEFAULT 'CREATED',
    
    -- For authorization flow
    authorized_amount DECIMAL(10, 2),
    captured_amount DECIMAL(10, 2) DEFAULT 0.00,
    
    -- For refunds
    refunded_amount DECIMAL(10, 2) DEFAULT 0.00,
    refund_reason VARCHAR(500),
    
    -- Idempotency: Unique key to prevent duplicate payments
    idempotency_key VARCHAR(100) UNIQUE,
    
    -- Metadata
    payer_email VARCHAR(255),
    payer_name VARCHAR(255),
    approval_url VARCHAR(1000),
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    
    -- Foreign key
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

-- ============================================================
-- TABLE: subscriptions
-- Purpose: Store recurring payment subscriptions
-- Concepts:
--   - plan_id: PayPal billing plan identifier
--   - billing_cycle: MONTHLY, YEARLY, etc.
--   - next_billing_date: When next payment occurs
-- ============================================================
CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- PayPal identifiers
    paypal_subscription_id VARCHAR(100) UNIQUE,
    paypal_plan_id VARCHAR(100) NOT NULL,
    
    -- Subscription details
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'USD',
    
    -- Billing cycle: DAILY, WEEKLY, MONTHLY, YEARLY
    billing_cycle VARCHAR(20) DEFAULT 'MONTHLY',
    billing_interval INT DEFAULT 1,
    
    -- Status: ACTIVE, SUSPENDED, CANCELLED, EXPIRED
    status VARCHAR(20) DEFAULT 'PENDING',
    
    -- Customer info
    subscriber_email VARCHAR(255),
    subscriber_name VARCHAR(255),
    
    -- Dates
    start_date DATE,
    next_billing_date DATE,
    cancelled_at TIMESTAMP,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- TABLE: webhook_events
-- Purpose: Store PayPal webhook notifications
-- Concepts:
--   - event_type: PAYMENT.CAPTURE.COMPLETED, etc.
--   - processed: Track if event was handled
--   - idempotency: event_id is unique to prevent duplicate processing
-- ============================================================
CREATE TABLE webhook_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- PayPal webhook data
    event_id VARCHAR(100) UNIQUE NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    resource_type VARCHAR(50),
    resource_id VARCHAR(100),
    
    -- Full webhook payload (JSON)
    payload TEXT,
    
    -- Processing status
    processed BOOLEAN DEFAULT FALSE,
    processed_at TIMESTAMP,
    error_message VARCHAR(1000),
    retry_count INT DEFAULT 0,
    
    -- Timestamps
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- TABLE: payment_items
-- Purpose: Store line items for payments (for detailed receipts)
-- ============================================================
CREATE TABLE payment_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    quantity INT DEFAULT 1,
    unit_price DECIMAL(10, 2) NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    sku VARCHAR(100),
    
    CONSTRAINT fk_item_payment FOREIGN KEY (payment_id) REFERENCES payments(id)
);

-- ============================================================
-- Indexes for better query performance
-- ============================================================
CREATE INDEX idx_payments_status ON payments(status);
CREATE INDEX idx_payments_paypal_id ON payments(paypal_payment_id);
CREATE INDEX idx_payments_idempotency ON payments(idempotency_key);
CREATE INDEX idx_orders_number ON orders(order_number);
CREATE INDEX idx_subscriptions_status ON subscriptions(status);
CREATE INDEX idx_webhook_events_type ON webhook_events(event_type);
CREATE INDEX idx_webhook_events_processed ON webhook_events(processed);
